# Generated by Django 3.1.2 on 2020-10-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaArgenti', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
